### ISSUE TITLE
How to install this exactly?

### ISSUE THREAD

**Issue by hakunin** [hwartig/vim-seeing-is-believing#10]
I added:
```
Plug 'hwartig/vim-seeing-is-believing'
```

Reloaded the file, did `:PlugInstall` and opened the editor again.

Immediately I get this:
```
No such group or event: FiteType ruby nmap <buffer> <Enter> <Plug>(seeing-is-believing-mark-and-run)
```

What do I need to do to get this installed properly?

**Comment by brandoncc** [comment]
I believe "FiteType" is a typo, it should be "FileType".

Hopefully that will get you up and running!

**Comment by hakunin** [comment]
That was it, thanks!
