### ISSUE TITLE
Is there any way to clear the annotations?

### ISSUE THREAD

**Issue by collegeimprovements** [hwartig/vim-seeing-is-believing#7]
Hello, thanks for this awesome gem.
I was wondering if there is any way to clear the # => pattern ? 

It works fine if we undo it but it's a little cumbersome to clear it to remove the pattern afterwards!

Thanks.

**Comment by brandoncc** [comment]
Your question prompted me to figure out an easy way to do this, so I created a couple of mappings which handle this nicely:

```
" ~/.vimrc

" Seeing is believing mapping
nmap <F5> <Plug>(seeing-is-believing-mark)
xmap <F5> <Plug>(seeing-is-believing-mark)
imap <F5> <Plug>(seeing-is-believing-mark)

nmap <F6> <Plug>(seeing-is-believing-run)
xmap <F6> <Plug>(seeing-is-believing-run)
imap <F6> <Plug>(seeing-is-believing-run)

nmap <F7> :%s/\s\+# =>.*$//g<CR>
xmap <F7> :s/\s\+# =>.*$//g<CR>
```

If I press F7 with nothing selected, I remove the pattern from my entire file. If I select line(s) first, I remove the pattern from only those lines. I hope helps :smile:

**Comment by collegeimprovements** [comment]
This pattern works. Thanks :) you rock.

**Comment by collegeimprovements** [comment]
To clear evaluated lines (e.g. `# >> "hi"`) , the regex `:%s/^#\s>>\s.*$//g` can be used.

Can we combine them both so `<F7>` key can remove all the annotations?

**Comment by brandoncc** [comment]
Sure, just use an alternation (`\|`):

```
:%s/\s\+# =>.*$\|^#\s\[>!~]>\s.*$//g
```

We can actually go even a bit further than that though. Errors and output to `STDERR` have a different notation:

```
puts "a"
STDERR.puts "b"
puts c

# >> a

# !> b

# ~> NameError
# ~> undefined local variable or method `c' for main:Object
# ~>
# ~> /var/folders/90/fcqtbbx91_s78br0my1wzm7w0000gn/T/seeing_is_believing_temp_dir20151025-15079-lm18me/program.rb:3:in `<main>'
```

As you can see those have `~>` and `!>`. You can use:

```
:%s/\s\+# =>.*$\|^#\s[>!\~]>\(\s.*\)\?$//g
```

to clean all of the output above. Note that I had to make the whitespace and string after `>` an optional group or else the second to last line would not be removed. Once you do that, you may want to do some cleanup of the leftover blank lines.

You can do that with:

```
nmap <F7> :%s/\s\+# =>.*$\\|^#\s[>!\~]>\(\s.*\)\?$//g \| :%s#\($\n\s*\)\+\%$##<CR>
xmap <F7> :s/\s\+# =>.*$\\|^#\s[>!\~]>\(\s.*\)\?$//g \| :'<,'>s#\($\n\s*\)\+\%$##<CR>

```

Please note that I got the blank line regex [here](http://stackoverflow.com/a/7496112/617243).
