### ISSUE TITLE
V-LINE issue

### ISSUE THREAD

**Issue by cj** [hwartig/vim-seeing-is-believing#8]
When visually selecting code like:

```
a = 1
b = 2
a + b
```

I get this error: `Too many arguments for function: seeing_is_believing#mark_and_run_visual`

**Comment by cj** [comment]
Tried `vim-ruby-xmpfilter`, visually selecting and running a block of code works just fine.

**Comment by Gaolz** [comment]
@cj No problem in my vim

**Comment by hwartig** [comment]
I know you just assigned this issue to me.  I am currently paddling through Neuvenedig (New Venice)!  I will be back on 5/29. Will respond then.

**Comment by hwartig** [comment]
Hey @cj :wave: sorry for being so unresponsive. I hope the issue resolved for you as well. Feel free to reopen if not.
